apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webapp.fullname" . }}-frontend
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webapp.fullname" . }}-backend
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
automountServiceAccountToken: false

